package org.openapi.quarkus.swagger_json.api;


import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider; 
import org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders;
import org.openapi.quarkus.swagger_json.api.auth.CompositeAuthenticationProvider;
import org.openapi.quarkus.swagger_json.api.auth.AuthenticationPropagationHeadersFactory;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;

import jakarta.enterprise.context.ApplicationScoped;

import io.quarkiverse.openapi.generator.annotations.GeneratedClass;
import io.quarkiverse.openapi.generator.annotations.GeneratedMethod;
import io.quarkiverse.openapi.generator.annotations.GeneratedParam;

/**
  * Ansible Automation Platform controller API
  * <p/>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  */
@Path("/api/v2/analytics")
@RegisterRestClient(baseUri="https://null/", configKey="swagger_json")
@GeneratedClass(value="swagger.json", tag = "AutomationAnalytics")
@RegisterProvider(CompositeAuthenticationProvider.class)
@RegisterClientHeaders(AuthenticationPropagationHeadersFactory.class)
@ApplicationScoped
public interface AutomationAnalyticsApi {

    @POST
    @Path("/adoption_rate/")
    @GeneratedMethod ("Automation Analytics_analytics_adoption_rate_create")
    public void automationAnalyticsAnalyticsAdoptionRateCreate(
    );

    @GET
    @Path("/adoption_rate/")
    @GeneratedMethod ("Automation Analytics_analytics_adoption_rate_list")
    public void automationAnalyticsAnalyticsAdoptionRateList(
    );

    @POST
    @Path("/adoption_rate_options/")
    @GeneratedMethod ("Automation Analytics_analytics_adoption_rate_options_create")
    public void automationAnalyticsAnalyticsAdoptionRateOptionsCreate(
    );

    @GET
    @Path("/adoption_rate_options/")
    @GeneratedMethod ("Automation Analytics_analytics_adoption_rate_options_list")
    public void automationAnalyticsAnalyticsAdoptionRateOptionsList(
    );

    @POST
    @Path("/authorized/")
    @GeneratedMethod ("Automation Analytics_analytics_authorized_create")
    public void automationAnalyticsAnalyticsAuthorizedCreate(
    );

    @GET
    @Path("/authorized/")
    @GeneratedMethod ("Automation Analytics_analytics_authorized_list")
    public void automationAnalyticsAnalyticsAuthorizedList(
    );

    @POST
    @Path("/event_explorer/")
    @GeneratedMethod ("Automation Analytics_analytics_event_explorer_create")
    public void automationAnalyticsAnalyticsEventExplorerCreate(
    );

    @GET
    @Path("/event_explorer/")
    @GeneratedMethod ("Automation Analytics_analytics_event_explorer_list")
    public void automationAnalyticsAnalyticsEventExplorerList(
    );

    @POST
    @Path("/event_explorer_options/")
    @GeneratedMethod ("Automation Analytics_analytics_event_explorer_options_create")
    public void automationAnalyticsAnalyticsEventExplorerOptionsCreate(
    );

    @GET
    @Path("/event_explorer_options/")
    @GeneratedMethod ("Automation Analytics_analytics_event_explorer_options_list")
    public void automationAnalyticsAnalyticsEventExplorerOptionsList(
    );

    @POST
    @Path("/host_explorer/")
    @GeneratedMethod ("Automation Analytics_analytics_host_explorer_create")
    public void automationAnalyticsAnalyticsHostExplorerCreate(
    );

    @GET
    @Path("/host_explorer/")
    @GeneratedMethod ("Automation Analytics_analytics_host_explorer_list")
    public void automationAnalyticsAnalyticsHostExplorerList(
    );

    @POST
    @Path("/host_explorer_options/")
    @GeneratedMethod ("Automation Analytics_analytics_host_explorer_options_create")
    public void automationAnalyticsAnalyticsHostExplorerOptionsCreate(
    );

    @GET
    @Path("/host_explorer_options/")
    @GeneratedMethod ("Automation Analytics_analytics_host_explorer_options_list")
    public void automationAnalyticsAnalyticsHostExplorerOptionsList(
    );

    @POST
    @Path("/job_explorer/")
    @GeneratedMethod ("Automation Analytics_analytics_job_explorer_create")
    public void automationAnalyticsAnalyticsJobExplorerCreate(
    );

    @GET
    @Path("/job_explorer/")
    @GeneratedMethod ("Automation Analytics_analytics_job_explorer_list")
    public void automationAnalyticsAnalyticsJobExplorerList(
    );

    @POST
    @Path("/job_explorer_options/")
    @GeneratedMethod ("Automation Analytics_analytics_job_explorer_options_create")
    public void automationAnalyticsAnalyticsJobExplorerOptionsCreate(
    );

    @GET
    @Path("/job_explorer_options/")
    @GeneratedMethod ("Automation Analytics_analytics_job_explorer_options_list")
    public void automationAnalyticsAnalyticsJobExplorerOptionsList(
    );

    @GET
    @GeneratedMethod ("Automation Analytics_analytics_list")
    public void automationAnalyticsAnalyticsList(
    );

    @POST
    @Path("/probe_template_for_hosts/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_template_for_hosts_create")
    public void automationAnalyticsAnalyticsProbeTemplateForHostsCreate(
    );

    @GET
    @Path("/probe_template_for_hosts/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_template_for_hosts_list")
    public void automationAnalyticsAnalyticsProbeTemplateForHostsList(
    );

    @POST
    @Path("/probe_template_for_hosts_options/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_template_for_hosts_options_create")
    public void automationAnalyticsAnalyticsProbeTemplateForHostsOptionsCreate(
    );

    @GET
    @Path("/probe_template_for_hosts_options/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_template_for_hosts_options_list")
    public void automationAnalyticsAnalyticsProbeTemplateForHostsOptionsList(
    );

    @POST
    @Path("/probe_templates/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_templates_create")
    public void automationAnalyticsAnalyticsProbeTemplatesCreate(
    );

    @GET
    @Path("/probe_templates/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_templates_list")
    public void automationAnalyticsAnalyticsProbeTemplatesList(
    );

    @POST
    @Path("/probe_templates_options/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_templates_options_create")
    public void automationAnalyticsAnalyticsProbeTemplatesOptionsCreate(
    );

    @GET
    @Path("/probe_templates_options/")
    @GeneratedMethod ("Automation Analytics_analytics_probe_templates_options_list")
    public void automationAnalyticsAnalyticsProbeTemplatesOptionsList(
    );

    @POST
    @Path("/report/{slug}/")
    @GeneratedMethod ("Automation Analytics_analytics_report_create")
    public void automationAnalyticsAnalyticsReportCreate(
        @GeneratedParam("slug") @PathParam("slug") String slug
    );

    @POST
    @Path("/report_options/")
    @GeneratedMethod ("Automation Analytics_analytics_report_options_create")
    public void automationAnalyticsAnalyticsReportOptionsCreate(
    );

    @GET
    @Path("/report_options/")
    @GeneratedMethod ("Automation Analytics_analytics_report_options_list")
    public void automationAnalyticsAnalyticsReportOptionsList(
    );

    @GET
    @Path("/report/{slug}/")
    @GeneratedMethod ("Automation Analytics_analytics_report_read")
    public void automationAnalyticsAnalyticsReportRead(
        @GeneratedParam("slug") @PathParam("slug") String slug
    );

    @POST
    @Path("/reports/")
    @GeneratedMethod ("Automation Analytics_analytics_reports_create")
    public void automationAnalyticsAnalyticsReportsCreate(
    );

    @GET
    @Path("/reports/")
    @GeneratedMethod ("Automation Analytics_analytics_reports_list")
    public void automationAnalyticsAnalyticsReportsList(
    );

    @POST
    @Path("/roi_templates/")
    @GeneratedMethod ("Automation Analytics_analytics_roi_templates_create")
    public void automationAnalyticsAnalyticsRoiTemplatesCreate(
    );

    @GET
    @Path("/roi_templates/")
    @GeneratedMethod ("Automation Analytics_analytics_roi_templates_list")
    public void automationAnalyticsAnalyticsRoiTemplatesList(
    );

    @POST
    @Path("/roi_templates_options/")
    @GeneratedMethod ("Automation Analytics_analytics_roi_templates_options_create")
    public void automationAnalyticsAnalyticsRoiTemplatesOptionsCreate(
    );

    @GET
    @Path("/roi_templates_options/")
    @GeneratedMethod ("Automation Analytics_analytics_roi_templates_options_list")
    public void automationAnalyticsAnalyticsRoiTemplatesOptionsList(
    );

}
